//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b01 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 05:46:03 PM CST 
//


package com.jieh.core.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jiehang.core.context.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Components_QNAME = new QName("http://www.jiehang.com/autumn/schema/components", "components");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jiehang.core.context.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentsConfig }
     * 
     */
    public ComponentsConfig createComponentsConfig() {
        return new ComponentsConfig();
    }

    /**
     * Create an instance of {@link ComponentConfig }
     * 
     */
    public ComponentConfig createComponentConfig() {
        return new ComponentConfig();
    }

    /**
     * Create an instance of {@link PropertyConfig }
     * 
     */
    public PropertyConfig createPropertyConfig() {
        return new PropertyConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentsConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jiehang.com/autumn/schema/components", name = "components")
    public JAXBElement<ComponentsConfig> createComponents(ComponentsConfig value) {
        return new JAXBElement<ComponentsConfig>(_Components_QNAME, ComponentsConfig.class, null, value);
    }

}
